Feature/edit profile
Arkant/AngularJSMiniApp pull request #85
Opened 2019-03-18 18:50 UTC by Vladislav-Shvorobuk

2019-03-18 19:13 UTC, pseudopilot requested changes

2019-03-18 19:13 UTC, RuQuentin commented on src/app/core/services/user-profile.service.js
>        };
Please, replace all this method `saveToCurrentUser` with the following one.
I forgot to do it last time. And it does the same but shorter

```
this.saveToCurrentUser = function (data) {
        $rootScope.currentUser = Object.assign($rootScope.currentUser, data);
      };
```

2019-03-18 19:32 UTC, pseudopilot submitted a review, later dismissed

2019-03-18 19:32 UTC, RuQuentin commented on src/app/core/services/user-profile.service.js
>        };
Please, replace it with the following code:
```
      this.createFormInfo = function () {
        const formInfo = Object.assign({}, $rootScope.currentUser);
        return formInfo;
      };
```

2019-03-18 21:50 UTC, motifej requested changes

2019-03-18 21:50 UTC, motifej commented on src/app/core/filter/phone.filter.js
> +        return  function (value) {
DRY - one of princip

2019-03-19 10:34 UTC, Arkant approved these changes

2019-03-19 10:34 UTC, ElenaBorisenkoO approved these changes

2019-03-19 15:17 UTC, motifej approved these changes

2019-03-19 15:23 UTC, merged